# Generated by Django 5.2.3 on 2026-05-12 15:07

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4, WebM, etc.)', null=True, upload_to=blogs.models.blog_video_upload_path),
        ),
    ]
