# Generated by Django 6.0 on 2025-12-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_sociallink_alter_about_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
